version: '3.4'

services:
  webapi:
    build:
      context: ./src/WebApi5
      dockerfile: Dockerfile
    expose:
      - 5000
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Development
    restart: always
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - webapi
    restart: always
    